### ISSUE TITLE
/app/controllers/application.rb needs renaming

### ISSUE THREAD

**Issue by jedschneider** [collectiveidea/audit-demo#1]
This may be rails 2.3.2 specific but I needed to rename the file to application_controller.rb in order for mongrel to serve the request without failing with the following NameError 
"NameError (uninitialized constant ApplicationController): app/controllers/pages_controller.rb:1"

**Comment by asheren** [comment]
Hi there! We're doing some open source maintenance work and closing old issues. If this issue is still applicable or you would still like it to be addressed, please re-open the issue by April 17, 2017. Thanks!
